- name: Include task Example
  hosts: all
  tasks:
    - name: Print debug
      ansible.builtin.debug:
        msg: print Debug msg

    - name: Include a file
      ansible.builtin.include_tasks:
        file: universal.yml

    - name: import a file
      ansible.builtin.import_tasks:
        file: universal.yml