- name: Declare variable
  hosts: all
  vars:
    URL: example.com

  tasks:
    - name: Print the URL variable
      ansible.builtin.debug:
        msg: URL - {{ URL }} ## bash ${} single flower braces, Ansible {{}}
