- name: Demo on Loops
  hosts: localhost
  connection: local
  tasks:

      ansible.builtin.debug:
        msg: Fruit Name - {{ item }}
      loop:
        - banana
        - apple
        - orange
        - apple