- name: Register variable
  hosts: localhost
  connection: local
  tasks:
    - name: uptime for shell
      ansible.builtin.shell: uptime
      register: out

    - name: print output
      ansible.builtin.debug:
        msg: "{{ out }}"