- name: Print parameter from Parameter Store
  hosts: localhost
  connection: local
  tasks:
    - name: print parameters
      ansible.builtin.debug:
        msg: "parameter - {{ lookup('amazon.aws.aws_ssm', 'roboshop.dev.frontend.catalogue_url', region='us-east-01') }}"