- name: Demo on Template
  hosts: localhost
  connection: local
  vars:
    fruit_name: apple
    quantity: 100
  tasks:
    - name: Copy a file
      ansible.builtin.template:
        src: test.txt
        dest: /tmp/test.txt

